### ISSUE TITLE
Permission issue when trying to access the socket?

### ISSUE THREAD

**Issue by ArchangeGabriel** [poolpOrg/filter-rspamd#49]
I’ve setup the worker-normal socket to be `660 rspamd:rspamd` (0660 in octal mode for the configuration file), but also added `smtpd` user to the `rspamd` group.

However, when smtpd starts in this configuration, it fails with:
```
'/run/rspamd/normal.sock' err: 'dial unix /run/rspamd/normal.sock: connect: permission denied'
```

It works OK if the socket is `666`, but I think this is not a good idea from a security standpoint.

**Comment by xc3seziu** [comment]
It's been a minutes since I've used `rspamd` but I believe you can change its group user to match the mailer daemon with no ill effects. Do the same for its directory and remove "other" permissions entirely. You'll need to restart `rspamd` after changing its group. Also watch your logs to ensure it's not being denied permissions anywhere--though I don't expect you'll have any problems here.

If you can send the permission of /run and /run/rspamd, as well as the socket file, I may be able to give you specific permissions so that the directory tree is traversable by the mailer daemon and the socket is readable and writeable only by `rspamd` and `smptd`. Without it being readable by "other".

Also, what OS and version are you running?

It can get a little tricky when tightening permissions like this, but it's certainly possible as I tend to do similar things.

**Comment by ArchangeGabriel** [comment]
I would prefer to avoid giving `rspamd` the `smtpd` group, I trust smtpd more than rspamd. I’m running Arch Linux, so latest version of everything available there (that is 7.3.0p1 for smtpd itself and 0.1.8 for the rspamd filter).

Current permissions are:
```
drwxr-xr-x root root /run
drwxr-xr-x rspamd rspamd /run/rspamd
srw-rw-rw- rspamd rspamd /run/rspamd/normal.sock
```
But the ones I’m trying to achieve are `srw-rw----` for the socket. It works OK for `controller.sock` with the `http` user of nginx being in the `rspamd` group, but not for smtpd… Is it running the filter with the permissions associated with the smtpd user/group?

**Comment by xc3seziu** [comment]
You could give the `smtpd` process the `rspamd` group instead. This way the `smtpd` _process_ is running with the `rspamd` group instead of the `smtpd` group. (Which mail server software are you running, BTW?)

If this is a multi-user box, or if you want to provide better security in the case of errant processes not running as root, you could then do something like this:

drwxr-x--- rspamd rspamd /run/rspamd
srw-rw---- rspamd rspamd /run/rspamd/normal.sock

Not all processes will pick up or run with group memberships, so the processes themselves sometimes needs to be configured to run with the specific group (versus adding them to groups through /etc/group or however you do that on Arch).

Another option, though potentially less secure on multi-user Linux boxes, is to use TCP ports instead of sockets. Then file system permissions would be negated. On OpenBSD, one can add firewall rules to restrict port access to a given user or (I think) process--not sure if this is available with a Linux firewall, though.

Yet another option... You could implement SELinux. SELinux has many controls for such things. Many (many) people don't like SELinux, but it's really a great security framework. AppArmour may have similar options and might be a little easier to configure, but I'm not too familiar with it.

**Comment by ArchangeGabriel** [comment]
Yeah, in the long run my plan is to implement SELinux, but this is a huge task. I’m not sure about port access limitation, as a matter of fact I’m actually trying to use socket to indeed avoid a local port available to everyone.

I guess you’re right that the group is somehow not picked up by the process running the filter, that’s mostly what I’m asking here in fact (and whether that is expected).

Maybe I should try ACL instead, just need to check how to configure them for a file that is not permanently on the system (maybe in a droppin snippet running after the start of rspamd).

**Comment by xc3seziu** [comment]
SELinux really isn't a huge task. Install. Label file system. Reboot. Done. If you're running software that SELinux doesn't have policies for, or you've customized things in a non-standard way, you'll need to create or modify policies to support these customizations--that may take a little effort. But otherwise, it's generally fairly easy to do.

It's generally recommended to start SELinux in permissive mode and allow some time for the audit logs to populate with possible errors or permissions issue.

There's a command that you can run against the audit log that will tell you which rules need to be added.

It can get a little tricky at times, and you really have to understand how Linux works to properly setup SELinux policies. But otherwise, SELinux isn't all that difficult.

This might help, if you aren't already familiar with the information on this page: https://www.redhat.com/sysadmin/selinux-denial2

**Comment by poolpOrg** [comment]
I don't think there's anything I can do in the filter itself:

- either use HTTP mode
- or permissions on the filesystem must be correct to access the socket

As suggested by @xc3seziu maybe run the filter with different group.

Note that filters do not need to run as _smtpd, there's an option for them to drop privileges to a different group, so the filter-rspamd code could run as _rspamd regardless of what the daemon itself runs as.

**Comment by ArchangeGabriel** [comment]
@poolpOrg Ah, I missed the fact we could run filter as a different user/group, it is not shown on https://man.openbsd.org/smtpd.conf#filter~4

But there is actually an example with _dkimsign in the https://man.openbsd.org/smtpd.conf#EXAMPLES section, nice. Will try that!

EDIT: That worked perfectly.
